config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    resources :bookings, only: :create
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :studios
  resources :bookings # do we need all of the routes for bookings?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :studio
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: {only_integer: true}
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :users
  has_many :courses
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews, through: :courses
  
  CATEGORY = Studio.select(:category).map(&:category).uniq.reject(&:blank?)
  LOCATION = Studio.select(:address).map(&:address).uniq.reject(&:blank?)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  belongs_to :studio, optional: true
  has_many :courses, through: :bookings
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]

  def index
    @courses = current_user.courses
    @flag = ""
    @past_courses = @courses.where('time < ?', Time.now)
    @upcoming_courses = @courses.where('time > ?', Time.now).order(:time)
  end

  def show
    # Don't think this method is required
  end

  def create
    @course = Course.find(params[:course_id])
    @booking = Booking.new(course: Course.find(params[:course_id]))
    @booking.course = @course
    @booking.user = current_user
    # TODO : change this for curent user once devise is done !!!!
    # @booking.user = User.first
    if @booking.save
      redirect_to bookings_path
    else
      @studios = Studio.all
      render 'studios/index'
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def set_params
    params.require(:course).permit(:studio_id, :name, :time, :duration, :price, :capacity, :difficulty, :teacher_name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @course = Course.find(params[:course_id])
    @review = Review.new
  end

  def create
    @course = Course.find(params[:course_id])
    @studio = @course.studio
    @review = Review.new(set_params)
    @review.course = @course
    @review.user = current_user
    if @review.save
      redirect_to studio_path(@studio)
    else
      render :new
    end
  end

  private

  def set_params
    params.require(:review).permit(:title, :content, :rating, :user_id, :course_id)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  
  def index
    @studios = Studio.geocoded
    @bookings = current_user.bookings
    if params[:search].present?
      @location = params[:search][:location]
      @category = params[:search][:category]
      @studios = Studio.where("address ILIKE ? AND category ILIKE ?", "%#{@location}%", "%#{@category}%")
    end

    @markers = @studios.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { studio: studio })
      }
    end
  end

  def show
    @studio = Studio.find(params[:id])
    pp @studio
    reviews = @studio.reviews.includes(:course, :user)
    pp reviews
    course_reviews = reviews.group_by { |r| r.course.name }
    pp course_reviews
    @course_teacher_reviews = course_reviews.map { |k,v| [k, v.group_by { |r| r.course.teacher_name } ]}.to_h
    pp @course_teacher_reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_card.html.erb
<div class="card-booking <%= card_class %>">
  <div class="card-booking-infos">
      <div class="card-booking-infos-left">
         <p><strong>Studio name</strong> : <%= course.studio.name %></p>
          <p><strong>Class name</strong> : <%= course.name %></p>
          <p><strong>Date : </strong><%= course.time.strftime('%a %b %e %l %p') %></p>
      </div>
      <div class="card-booking-infos-right">
        <% if past_course %>
          <%= link_to new_course_review_path(course) do %>
            <i class="far fa-comment icon-rose"></i>
          <% end %>
        <% else %>
          <%= link_to booking_path(course.bookings.find_by(user: current_user)), method: :delete, data: {"confirm-swal": "Are you sure?"} do %>
            <i class="far fa-trash-alt icon-rose"></i>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/bookings/index.html.erb
<div class=booking-container>
  <h1 class="text-center my-3">My Bookings</h1>
    <div class="icons-booking">
    <%= link_to root_path do %>
    <i class="fas fa-home"></i>
    <% end %>
    <%= link_to studios_path do %>
    <i class="fas fa-backward"></i>
    <% end %>
    </div>

    <h3>Upcoming classes</h3>
    <% if @upcoming_courses.any? %>
      <% @upcoming_courses.each do |course| %>
        <%= render 'bookings/card', course: course, card_class: 'card-booking-white', past_course: false %>
      <% end %>
    <% else %>
      <div class='card-booking card-booking-white'>
        <p>No upcoming class yet! Make sure you book <%= link_to "one", studios_path %>!</p>
      </div>
    <% end %>

    <h3>Past classes</h3>
    <% if @past_courses.any? %>
      <% @past_courses.each do |course| %>
        <%= render 'bookings/card', course: course, card_class: 'card-booking-gray', past_course: true %>
      <% end %>
    <% else %>
      <div class='card-booking card-booking-white'>
        <p>No past class!</p>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fitpass</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-video-wrapper">
  <%= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, class: "home_video" %>
  <h1 class="home">One Pass. Every Class. Tokyo.</h1>
  <p class="home">Commit to your fitness, not to a gym.</p>
  <p class="home">Join us and work out at any gym, try any workout and do it all with one pass.</p>

<%= link_to 'Book a class', studios_path, class: "btn btn-rose" %>
</div>

app/views/reviews/new.html.erb
<div class="container my-5">
    <h1 class="text-center mb-3">Add a New Review</h1>
    <div class="row mt-3 justify-content-center pt-3">
        <div class="col-6">
            <%= simple_form_for [@course, @review] do |f| %>
            <%= f.input :title %>
            <%= f.input :content %>
            <%= f.input :rating, collection: 0..5%>
            <%= f.button :submit, "Add review", class: "btn btn-rose" %>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <a class="hover-underline-animation" href="#">Privacy Policy</a>
    <a class="hover-underline-animation" href="#">Terms of Use</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars1.githubusercontent.com/u/47027511?s=400&u=5ec326d7871394fb833967fb221f1966649220d7&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/studios/_info_window.html.erb
<h2><%= studio.name %></h2>
<p><%#= studio.address %></p>

app/views/studios/index.html.erb
<div class="justify-content-center d-flex">
<%= simple_form_for :search, url: studios_path, method:'GET', html: {class: 'form-inline'} do |f| %>
    <div class="form-group mb-2 mx-2 rose-studio-copy">
          <%= f.input :category, collection: Studio::CATEGORY, input_html: {class: 'form-control rose_studio_category'}, required: false, selected: @category, include_blank: 'All' %>
    </div>
    <div class="form-group mx-2 mb-2 rose-studio-copy">
          <%= f.input :location, collection: Studio::LOCATION, input_html: {class: 'form-control mr-2 rose_studio_category'}, required: false, selected: @location, include_blank: 'All' %>
    </div>
    <div class="form-group">
          <%= f.submit "Search", class: "btn rose_studio_button mb-2 mx-2" %>
    </div>
      <% end %>
</div>
<div class="studios-container d-flex">
  <div id="map" style="width: 400px; height: 100vh; position: sticky; top: 0px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  <div class="all-studios">
      <% @studios.each do |studio| %>
        <div class="d-flex">
          <div class="studio-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path studio.photo, height: 300, width: 400, crop: :fill %>')">
            <p class="studio-name"><%= studio.name %></p>
            <%= link_to "", studio_path(studio), class: 'studio-card-link' %>
            <p class="studio-info"><%= studio.description %></p>
          </div>

          <div class=" d-flex courses-card">
            <% studio.courses.order("time").each do |course| %>
              <% if course.time > Date.today %>
              <div>
                <div><%@flag = @bookings.any? {|booking| booking.course_id == course.id} %></div>
                <ul class="flex-column course-card p-0 m-0">
                  <!-- <div class="course-info-card"> -->
                    <p style="font-weight: bold"><%= course.name %><%@flag%></p>
                    <p><%= course.time.strftime('%A, %b %d') %></p>
                    <p><%= course.time.strftime('%l %p') %></p>
                    <p class ="extra-info"><%= course.teacher_name %> - <%= course.duration %> min - $<%= course.price %></p>
                   <!--  <#%= link_to "", course_path(course), class: 'course-card-link' %> -->
                  <!-- </div> -->
                  <div>
                    <%if @flag == false%>
                      <%= simple_form_for [course, Booking.new] do |f| %>
                        <%= f.submit "Book", class: 'booking-btn' %>
                      <% end %>
                    <% else  %>
                      <%= simple_form_for [course, Booking.new] do |f| %>
                      <%= f.submit "Booked ", class: 'booked-btn' %>
                      <% end %>
                    <% end %>
                  </div>
                </ul>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/studios/show.html.erb
<div class="bg-white">
  <div class="container_em bg-white border p-3 sticky-top">
    <div class="row d-flex">
      <div class="col-4">
        <div>
          <%= cl_image_tag @studio.photo, style: 'width: 100%', crop: :fill %>
        </div>
      </div>
      <div class="col-4">
        <h3><%=@studio.name%></h3>
        <p><%=@studio.description%></p>
      </div>
      <div class="col-4">
        <div class="bg-white border p-3 sticky-top">
        <div class="row justify-content-between" style="position: relative;">

          <div class="d-flex space-between">
            <a style="text-decoration:none;" href="#" class="rose-studio float-left mr-4 ml-2">Contact</a>
            <p class="ml-2 mr-2 mt-2">
              <span class="float-right"><i class="far fa-star" id="golden_star"></i></span>
              <span class="float-right"><i class="far fa-star" id="golden_star"></i></span>
              <span class="float-right"><i class="far fa-star" id="golden_star"></i></span>
              <span class="float-right"><i class="far fa-star" id="golden_star"></i></span>
            </p>
            <a style="text-decoration:none;" href="#bott" class="rose-studio float-left btn ml-4 mr-2">Reviews</a>

          </div>
        </div>
          <div class="d-flex justify-content-between mt-3">
            <p><strong>Address</strong></p>
            <p><%=@studio.address%></p>
          </div>
          <div class="d-flex justify-content-between mt-3">
            <p><strong>Telephone</strong></p>
            <p>09-342-765-23</p>
          </div>
          <div class="d-flex justify-content-between mt-3 border-botto  m">
            <p><strong>e-mail</strong></p>
            <p><%=@studio.email%></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h1><center>Available Slots</center></h1>
    <div class="row justify-content-md-center">
      <div class="col-md-6">

            <%@studio.courses.each do |course| %>
              <div>
                <ul class="card p-3 mb-3">
                  <div class="course-info-card">
                  <p><strong><%= course.name %></strong></p>
                  <p><strong>Level:</strong> <%= course.difficulty%></p>
                  <p><strong>Time:</strong> <%= course.time.to_formatted_s(:short) %></p>
                  <p><strong>Capacity:</strong> <%= course.capacity%></p>
                  <p><strong>Price:</strong> $<%= course.price%></p>
                  <p><strong>Duration: </strong><%= course.duration%> min</p>
                  <%= link_to "", course_path(course), class: 'course-info-card-link' %>
                  </div>
                  <div>
                  <%= simple_form_for [course, Booking.new] do |f| %>
                    <%= f.submit "Book", class: 'rose-studio' %>
                  <% end %>
                  </div>
                </ul>
              </div>
            <% end %>
        </div>
      </div>


  <h2 id="bott" class="text-center">Reviews</h2>
  <div class="justify-content-center mr-5">
    <ul>
    <% @course_teacher_reviews.each do |course_name, teacher_reviews| %>
      <div>
        <h4 style="color: #D6B2B1"><%= course_name %></h4>
        <ul>
          <% teacher_reviews.each do |teacher_name, reviews| %>
            <div>
              <p style="color: #D6B2B1"><strong>Teacher: </strong><em><%= teacher_name %></em></p>
              <ul>
                <% reviews.each do |review| %>
                  <div>
                    <div class="card p-3 m-3">
                        <div class="d-flex align-items-center">
                          <img src="https://avatars1.githubusercontent.com/u/55873437?v=4" class="avatar m-3"/>
                          <div class="w-50">
                            <a><strong><%= review.title %></strong></a>
                          <div class="d-flex">
                            <% review.rating.times do %>
                              <i class="far fa-star" id="golden_star"></i>
                            <% end %>
                          </div>
                          </div>
                            <p><%= review.content %></p>
                            <a style="text-decoration:none;" class="rose-studio ml-2" href="#"> Like</a>
                            <a style="text-decoration:none;"class="rose-studio ml-2"  href="#">Review</a>
                          </div>
                  </div>
                <% end %>
              </ul>
            </div>
          <% end %>
        </ul>
      </div>
    <% end %>
    </ul>
  </div>

</div>